/*
 * class Name:ESPL10
 * Description:This class is return to cover ESPL10.
 * Created by:Ashlesha 
 * Created Date:06/04/2021
 */





@isTest
public class ECS10Test {
    
    @isTest static void ECmethod(){
        
        ECS10 ec=new ECS10();
        ec.AccOppClosedWon();
        ec.AccountBillingState();
        ec.AccountMultiSelect();
        ec.aggregatemethod();
        ECS10.agrResult();
        ec.AParToChild();
        ec.ChildtoPaConMedia();
        ec.CNameJohn();
        ec.countdistinct();
        ec.DelInactiveAcc();
        ec.DmlMethod();
        ec.OpportunityHundredRecord();
        ec.ParToChildAccJohn();
        ec.TestSOSL();
        
    }

}