/*
 * class Name:ESPL9Set1Test
 * Description:This class is return to cover ESPL9Set1.
 * Created by:Ashlesha 
 * Created Date:05/04/2021
 */



@isTest
public class ESPL9Set1Test {
    
    @isTest static void frstmethod(){
        ESPL9Set1 espl=new ESPL9Set1();
        espl.even();
        ESPL9Set1.AdvancedForloop();
        Integer n;
        Integer m;
        String Operation;
        integer[] numbers;
        ESPL9Set1.printArray(n);
        espl.calculate();
        ESPL9Set1.Calculator(Operation, n, m);
        espl.childparentSoql();
        ESPL9Set1.countcon();
        ESPL9Set1.countOcurrences();
        espl.DatemethodToday();
        ESPL9Set1.Descending();
        ESPL9Set1.findDuplicate();
        ESPL9Set1.leadid();
        espl.minNum();
        //ESPL9Set1.SortAscending(numbers);
        espl.sumNum();
        ESPL9Set1.traditionalForloop();
        ESPL9Set1.Whileloop();
    
   }
}