/*
 * class Name:ESPL9Set2Test
 * Description:This class is return to cover ESPL9Set2Test.
 * Created by:Ashlesha 
 * Created Date:06/04/2021
 */




@isTest
public class ESPL9Set2Test {
    
    @isTest static void esplmethod(){
        Integer x;
        String y;
        ESPL9Set2 esp=new ESPL9Set2(x,y);
        ESPL9Set2.AccountNameA();
        ESPL9Set2.Aoccurrence();
        esp.CampaignsName();
        esp.DatemethodLastMod();
        ESPL9Set2.LengthStr();
        esp.ListInMap();
        ESPL9Set2.palindromeString();
        ESPL9Set2.primeOrnot();
        ESPL9Set2.UniqueNum();
        esp.oppid();
        
        
    }

}