/*
 * class Name:ESPL9Set3Test
 * Description:This class is return to cover ESPL9Set3Test.
 * Created by:Ashlesha 
 * Created Date:06/04/2021
 */




@isTest
public class ESPL9Set3Test {
    
    @isTest static void espmethodthree(){
        string str;
        ESPL9Set3 es=new ESPL9Set3();
        es.accidmethod();
        es.accMapmethod();
        es.callMethod();
        es.conRecord();
        es.conrecordmethod();
        es.DmlOperation();
        es.fibnumber();
        //ESPL9Set3.getcharOccur(str);
        es.helloworld();
        es.mapmethod();
        es.reverseString();
        es.SOQLMethod();
        es.StringWord();
        
    }

}