/*
 * class Name:OpportunityCloneHandlerTest
 * Description:This class is return to cover OpportunitycloneHandler.
 * Created by:Ashlesha 
 * Created Date:06/04/2021
 */




@isTest
public class OpportunityCloneHandlerTest {
    
    @isTest static void oppclonemethod(){
    
    List<Opportunity> opportunitylist=new List<Opportunity>();
    
    OpportunitycloneHandler.oppclone(opportunitylist);
    }

}